export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const CLEAR_INGREDIENT = 'CLEAR_INGREDIENT';
export const UPDATE_INGREDIENT = 'UPDATE_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
