export const TRY_FETCH_RECIPES = 'TRY_FETCH_RECIPES';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const ERROR_RECIPES = 'ERROR_RECIPES';

export const TRY_ADD_RECIPE = 'TRY_ADD_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';

export const TRY_UPDATE_RECIPE = 'TRY_UPDATE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';

export const TRY_DELETE_RECIPE = 'TRY_DELETE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
